# Generated by Django 5.2.7 on 2025-10-15 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_sala_alter_consultamedica_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamenMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_examen', models.CharField(max_length=100)),
                ('resultado', models.TextField(blank=True, null=True)),
                ('fecha_examen', models.DateField()),
                ('medico_responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examenes', to='api.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examenes', to='api.paciente')),
            ],
        ),
        migrations.RemoveField(
            model_name='especialidaddetallada',
            name='especialidad',
        ),
        migrations.DeleteModel(
            name='Sala',
        ),
        migrations.DeleteModel(
            name='EspecialidadDetallada',
        ),
    ]
