# Generated by Django 5.2.7 on 2025-10-15 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_examenmedico_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examenmedico',
            name='paciente',
        ),
        migrations.AlterField(
            model_name='examenmedico',
            name='medico_responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examenes_realizados', to='api.medico'),
        ),
        migrations.CreateModel(
            name='HistorialAtencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('diagnostico', models.TextField()),
                ('tratamiento', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('medico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historiales', to='api.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiales', to='api.paciente')),
            ],
        ),
        migrations.AddField(
            model_name='examenmedico',
            name='historial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='examenes', to='api.historialatencion'),
        ),
    ]
