# Generated by Django 5.2.7 on 2025-10-15 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_examenmedico_paciente_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tratamiento',
            new_name='Tratamientos',
        ),
    ]
